services:
  pg:
    image: postgres
    container_name: announces
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: test
   # volumes:
    #  - ./pg-volume:/var/lib/postgresql
    ports:
      - "5432:5432"